
name: sportradar-aws-azure-login
version: git
summary: Use Azure AD SSO to log into the AWS via CLI.
description: |
  To configure the aws-azure-login client run:-
  $ aws-azure-login --configure
  Once aws-azure-login is configured, you can log in. For the default profile, just run:-
  $ aws-azure-login
base: core18
confinement: strict

parts:
  sportradar-aws-azure-login:
    plugin: nodejs
      nodejs-version: 8
      nodejs-package-manager: npm
    source: .

apps:
  sportradar-aws-azure-login:
    command: aws-azure-login
